#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jun 24 00:59:36 +0000 2026
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_vga_controller_behav -key {Behavioral:sim_1:Functional:tb_vga_controller} -tclbatch tb_vga_controller.tcl -log simulate.log"
xsim tb_vga_controller_behav -key {Behavioral:sim_1:Functional:tb_vga_controller} -tclbatch tb_vga_controller.tcl -log simulate.log

